/* Generated by the Nim Compiler v2.2.2 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI1056964616 = {size: 0, kind: 14, base: null, node: null, finalizer: null};
var NTI134217742 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI33555836 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33555167 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555175 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555174 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555171 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555172 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
var NNI33555172 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555172.node = NNI33555172;
NTI33555174.base = NTI33555171;
NTI33555175.base = NTI33555171;
var NNI33555171 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555174, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555175, name: "up", sons: null}]};
NTI33555171.node = NNI33555171;
var NNI33555167 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555167.node = NNI33555167;
NTI33555171.base = NTI33555167;
NTI33555172.base = NTI33555171;
NTI134217741.base = NTI33555172;
NTI134217743.base = NTI134217741;
var NNI33555836 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554450, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554435, name: "Field1", sons: null}, 
{kind: 1, offset: "Field2", len: 0, typ: NTI33554450, name: "Field2", sons: null}]};
NTI33555836.node = NNI33555836;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
NTI134217751.base = NTI33555172;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
NTI134217749.base = NTI33555172;
var NNI134217742 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217742.node = NNI134217742;
NTI134217742.base = NTI134217741;
var NNI1056964616 = {kind: 2, offset: 0, typ: null, name: null, len: 4, sons: {"0": {kind: 1, offset: 0, typ: NTI1056964616, name: "wsrsConnecting", len: 0, sons: null}, 
"1": {kind: 1, offset: 1, typ: NTI1056964616, name: "wsrsOpen", len: 0, sons: null}, 
"2": {kind: 1, offset: 2, typ: NTI1056964616, name: "wsrsClosing", len: 0, sons: null}, 
"3": {kind: 1, offset: 3, typ: NTI1056964616, name: "wsrsClosed", len: 0, sons: null}}};
NTI1056964616.node = NNI1056964616;

function toJSStr(s_p0) {
  var result_33556910 = null;

    var res_33556964 = newSeq__system_u2507((s_p0).length);
    var i_33556965 = 0;
    var j_33556966 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556965 < (s_p0).length)) break Label2;
          var c_33556967 = s_p0[i_33556965];
          if ((c_33556967 < 128)) {
          res_33556964[j_33556966] = String.fromCharCode(c_33556967);
          i_33556965 += 1;
          }
          else {
            var helper_33556993 = newSeq__system_u2507(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556994 = c_33556967.toString(16);
                  if ((((code_33556994) == null ? 0 : (code_33556994).length) == 1)) {
                  helper_33556993.push("%0");;
                  }
                  else {
                  helper_33556993.push("%");;
                  }
                  
                  helper_33556993.push(code_33556994);;
                  i_33556965 += 1;
                  if ((((s_p0).length <= i_33556965) || (s_p0[i_33556965] < 128))) {
                  break Label3;
                  }
                  
                  c_33556967 = s_p0[i_33556965];
                }
            };
++excHandler;
            try {
            res_33556964[j_33556966] = decodeURIComponent(helper_33556993.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            res_33556964[j_33556966] = helper_33556993.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556966 += 1;
        }
    };
    if (res_33556964.length < j_33556966) { for (var i = res_33556964.length ; i < j_33556966 ; ++i) res_33556964.push(null); }
               else { res_33556964.length = j_33556966; };
    result_33556910 = res_33556964.join("");

  return result_33556910;

}

function rawEcho() {
          var buf = "";
      for (var i = 0; i < arguments.length; ++i) {
        buf += toJSStr(arguments[i]);
      }
      console.log(buf);
    

  
}

function mnewString(len_p0) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; i++) {result[i] = 0;}
    return result;
  

  
}

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_p0, src_p1, ti_p2) {
  var result_33557321 = null;

    switch (ti_p2.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer__system_u2869(ti_p2))) {
      result_33557321 = src_p1;
      }
      else {
        result_33557321 = [src_p1[0], src_p1[1]];
      }
      
      break;
    case 19:
            if (dest_p0 === null || dest_p0 === undefined) {
        dest_p0 = {};
      }
      else {
        for (var key in dest_p0) { delete dest_p0[key]; }
      }
      for (var key in src_p1) { dest_p0[key] = src_p1[key]; }
      result_33557321 = dest_p0;
    
      break;
    case 18:
    case 17:
      if (!((ti_p2.base == null))) {
      result_33557321 = nimCopy(dest_p0, src_p1, ti_p2.base);
      }
      else {
      if ((ti_p2.kind == 17)) {
      result_33557321 = (dest_p0 === null || dest_p0 === undefined) ? {m_type: ti_p2} : dest_p0;
      }
      else {
        result_33557321 = (dest_p0 === null || dest_p0 === undefined) ? {} : dest_p0;
      }
      }
      nimCopyAux(result_33557321, src_p1, ti_p2.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_p1)) { 
        if(dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new src_p1.constructor(src_p1);
        } else {
          dest_p0.set(src_p1, 0);
        }
        result_33557321 = dest_p0;
      } else {
        if (src_p1 === null) {
          result_33557321 = null;
        }
        else {
          if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
            dest_p0 = new Array(src_p1.length);
          }
          result_33557321 = dest_p0;
          for (var i = 0; i < src_p1.length; ++i) {
            result_33557321[i] = nimCopy(result_33557321[i], src_p1[i], ti_p2.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_p1 === null) {
        result_33557321 = null;
      }
      else {
        if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new Array(src_p1.length);
        }
        result_33557321 = dest_p0;
        for (var i = 0; i < src_p1.length; ++i) {
          result_33557321[i] = nimCopy(result_33557321[i], src_p1[i], ti_p2.base);
        }
      }
    
      break;
    case 28:
            if (src_p1 !== null) {
        result_33557321 = src_p1.slice(0);
      }
    
      break;
    default: 
      result_33557321 = src_p1;
      break;
    }

  return result_33557321;

}

function arrayConstr(len_p0, value_p1, typ_p2) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; ++i) result[i] = nimCopy(null, value_p1, typ_p2);
    return result;
  

  
}

function cstrToNimstr(c_p0) {
      var ln = c_p0.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_p0.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_p0.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}

function raiseException(e_p0, ename_p1) {
    e_p0.name = ename_p1;
    if ((excHandler == 0)) {
    unhandledException(e_p0);
    }
    
    e_p0.trace = nimCopy(null, rawWriteStackTrace__system_u2180(), NTI33554449);
    throw e_p0;

  
}

function addInt(a_p0, b_p1) {
        var result = a_p0 + b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function chckRange(i_p0, a_p1, b_p2) {
  var result_33557361 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557361 = i_p0;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557361;

}

function chckIndx(i_p0, a_p1, b_p2) {
  var result_33557356 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557356 = i_p0;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_p0, a_p1, b_p2);
    }
    
  };

  return result_33557356;

}

function subInt(a_p0, b_p1) {
        var result = a_p0 - b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function divInt(a_p0, b_p1) {
        if (b_p1 == 0) raiseDivByZero();
    if (b_p1 == -1 && a_p0 == 2147483647) raiseOverflow();
    return Math.trunc(a_p0 / b_p1);
  

  
}

function reprEnum(e_p0, typ_p1) {
  var result_33557626 = [];

  var F = {procname: "system.reprEnum", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/system/reprjs.nim", line: 0};
  framePtr = F;
    F.line = 30;
    F.filename = "reprjs.nim";
    var tmp_33557627 = false;
    F.line = 31;
    var item_33557628 = typ_p1.node.sons[e_p0];
    F.line = 32;
    tmp_33557627 = item_33557628 !== undefined;
    if (tmp_33557627) {
    F.line = 34;
    result_33557626 = nimCopy(null, makeNimstrLit(item_33557628.name), NTI33554449);
    }
    else {
      F.line = 36;
      result_33557626 = nimCopy(null, (HEX24__systemZdollars_u8(e_p0)).concat([32,40,105,110,118,97,108,105,100,32,100,97,116,97,33,41]), NTI33554449);
    }
    
  framePtr = F.prev;

  return result_33557626;

}
var F = {procname: "module macros", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strformat", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/pure/strformat.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strformat", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/pure/strformat.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module dom", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/js/dom.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module dom", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/js/dom.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module close_event", prev: framePtr, filename: "/root/Projects/42/nimatcha/frontend/js/web_socket/close_event.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module close_event", prev: framePtr, filename: "/root/Projects/42/nimatcha/frontend/js/web_socket/close_event.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module message_event", prev: framePtr, filename: "/root/Projects/42/nimatcha/frontend/js/web_socket/message_event.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module message_event", prev: framePtr, filename: "/root/Projects/42/nimatcha/frontend/js/web_socket/message_event.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module include_patterns", prev: framePtr, filename: "/root/Projects/42/nimatcha/frontend/js/include_patterns.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module include_patterns", prev: framePtr, filename: "/root/Projects/42/nimatcha/frontend/js/include_patterns.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module web_socket", prev: framePtr, filename: "/root/Projects/42/nimatcha/frontend/js/web_socket/web_socket.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module web_socket", prev: framePtr, filename: "/root/Projects/42/nimatcha/frontend/js/web_socket/web_socket.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module web_socket", prev: framePtr, filename: "/root/Projects/42/nimatcha/frontend/js/web_socket.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module web_socket", prev: framePtr, filename: "/root/Projects/42/nimatcha/frontend/js/web_socket.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function newSeq__system_u2507(len_p0) {
  var result_33556943 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 653;
    F.filename = "system.nim";
    result_33556943 = new Array(len_p0); for (var i = 0 ; i < len_p0 ; ++i) { result_33556943[i] = null; }  framePtr = F.prev;

  return result_33556943;

}

function add__system_u1942(x_p0, x_p0_Idx, y_p1) {
          if (x_p0[x_p0_Idx] === null) { x_p0[x_p0_Idx] = []; }
      var off = x_p0[x_p0_Idx].length;
      x_p0[x_p0_Idx].length += y_p1.length;
      for (var i = 0; i < y_p1.length; ++i) {
        x_p0[x_p0_Idx][off+i] = y_p1.charCodeAt(i);
      }
    

  
}

function isFatPointer__system_u2869(ti_p0) {
  var result_33557303 = false;

  BeforeRet: {
    result_33557303 = !((ConstSet1[ti_p0.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557303;

}

function nimCopyAux(dest_p0, src_p1, n_p2) {
    switch (n_p2.kind) {
    case 0:
      break;
    case 1:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_p2.sons.length; i++) {
      nimCopyAux(dest_p0, src_p1, n_p2.sons[i]);
    }
    
      break;
    case 3:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
      for (var i = 0; i < n_p2.sons.length; ++i) {
        nimCopyAux(dest_p0, src_p1, n_p2.sons[i][1]);
      }
    
      break;
    }

  
}

function auxWriteStackTrace__system_u2084(f_p0) {
  var result_33556518 = [[]];

    var it_33556526 = f_p0;
    var i_33556527 = 0;
    var total_33556528 = 0;
    var tempFrames_33556529 = arrayConstr(64, {Field0: null, Field1: 0, Field2: null}, NTI33555836);
    Label1: {
        Label2: while (true) {
        if (!(!((it_33556526 == null)) && (i_33556527 <= 63))) break Label2;
          tempFrames_33556529[i_33556527].Field0 = it_33556526.procname;
          tempFrames_33556529[i_33556527].Field1 = it_33556526.line;
          tempFrames_33556529[i_33556527].Field2 = it_33556526.filename;
          i_33556527 += 1;
          total_33556528 += 1;
          it_33556526 = it_33556526.prev;
        }
    };
    Label3: {
        Label4: while (true) {
        if (!!((it_33556526 == null))) break Label4;
          total_33556528 += 1;
          it_33556526 = it_33556526.prev;
        }
    };
    result_33556518[0] = nimCopy(null, [], NTI33554449);
    if (!((total_33556528 == i_33556527))) {
    result_33556518[0].push.apply(result_33556518[0], [40]);;
    result_33556518[0].push.apply(result_33556518[0], HEX24__systemZdollars_u8((total_33556528 - i_33556527)));;
    result_33556518[0].push.apply(result_33556518[0], [32,99,97,108,108,115,32,111,109,105,116,116,101,100,41,32,46,46,46,10]);;
    }
    
    Label5: {
      var j_33556562 = 0;
      var colontmp__553648254 = 0;
      colontmp__553648254 = (i_33556527 - 1);
      var res_553648256 = colontmp__553648254;
      Label6: {
          Label7: while (true) {
          if (!(0 <= res_553648256)) break Label7;
            j_33556562 = res_553648256;
            result_33556518[0].push.apply(result_33556518[0], cstrToNimstr(tempFrames_33556529[j_33556562].Field2));;
            if ((0 < tempFrames_33556529[j_33556562].Field1)) {
            result_33556518[0].push.apply(result_33556518[0], [40]);;
            addInt__stdZprivateZdigitsutils_u241(result_33556518, 0, tempFrames_33556529[j_33556562].Field1);
            if (false) {
            result_33556518[0].push.apply(result_33556518[0], [44,32]);;
            addInt__stdZprivateZdigitsutils_u241(result_33556518, 0, 0);
            }
            
            result_33556518[0].push.apply(result_33556518[0], [41]);;
            }
            
            result_33556518[0].push.apply(result_33556518[0], [32,97,116,32]);;
            add__system_u1942(result_33556518, 0, tempFrames_33556529[j_33556562].Field0);
            result_33556518[0].push.apply(result_33556518[0], [10]);;
            res_553648256 -= 1;
          }
      };
    };

  return result_33556518[0];

}

function rawWriteStackTrace__system_u2180() {
  var result_33556613 = [];

    if (!((framePtr == null))) {
    result_33556613 = nimCopy(null, ([84,114,97,99,101,98,97,99,107,32,40,109,111,115,116,32,114,101,99,101,110,116,32,99,97,108,108,32,108,97,115,116,41,10]).concat(auxWriteStackTrace__system_u2084(framePtr)), NTI33554449);
    }
    else {
      result_33556613 = nimCopy(null, [78,111,32,115,116,97,99,107,32,116,114,97,99,101,98,97,99,107,32,97,118,97,105,108,97,98,108,101,10], NTI33554449);
    }
    

  return result_33556613;

}

function unhandledException(e_p0) {
    var buf_33556658 = [[]];
    if (!(((e_p0.message).length == 0))) {
    buf_33556658[0].push.apply(buf_33556658[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    buf_33556658[0].push.apply(buf_33556658[0], e_p0.message);;
    }
    else {
    buf_33556658[0].push.apply(buf_33556658[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    buf_33556658[0].push.apply(buf_33556658[0], [32,91]);;
    add__system_u1942(buf_33556658, 0, e_p0.name);
    buf_33556658[0].push.apply(buf_33556658[0], [93,10]);;
    buf_33556658[0].push.apply(buf_33556658[0], rawWriteStackTrace__system_u2180());;
    var cbuf_33556659 = toJSStr(buf_33556658[0]);
    framePtr = null;
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556659);
  }
  else {
    throw cbuf_33556659;
  }
  

  
}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_p0) {
        if (a_p0 > 2147483647 || a_p0 < -2147483648) raiseOverflow();
  

  
}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");

  
}

function addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, start_p2, n_p3) {
    var Temporary1;

  var F = {procname: "addChars.addChars", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 44;
    F.filename = "digitsutils.nim";
    var old_301990096 = (result_p0[result_p0_Idx]).length;
    F.line = 45;
    if (result_p0[result_p0_Idx].length < (Temporary1 = chckRange(addInt(old_301990096, n_p3), 0, 2147483647), Temporary1)) { for (var i = result_p0[result_p0_Idx].length; i < Temporary1; ++i) result_p0[result_p0_Idx].push(0); }
         else {result_p0[result_p0_Idx].length = Temporary1; };
    Label2: {
      F.line = 47;
      var iHEX60gensym4_301990110 = 0;
      F.line = 128;
      F.filename = "iterators_1.nim";
      var i_553648249 = 0;
      Label3: {
        F.line = 129;
          Label4: while (true) {
          if (!(i_553648249 < n_p3)) break Label4;
            F.line = 50;
            F.filename = "digitsutils.nim";
            iHEX60gensym4_301990110 = i_553648249;
            F.line = 47;
            result_p0[result_p0_Idx][chckIndx(addInt(old_301990096, iHEX60gensym4_301990110), 0, (result_p0[result_p0_Idx]).length - 1)] = x_p1.charCodeAt(chckIndx(addInt(start_p2, iHEX60gensym4_301990110), 0, (x_p1).length - 1));
            F.line = 131;
            F.filename = "iterators_1.nim";
            i_553648249 = addInt(i_553648249, 1);
          }
      };
    };
  framePtr = F.prev;

  
}

function addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, x_p1) {
  var F = {procname: "addChars.addChars", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 56;
    F.filename = "digitsutils.nim";
    addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, 0, ((x_p1) == null ? 0 : (x_p1).length));
  framePtr = F.prev;

  
}

function addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, x_p1) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 112;
    F.filename = "digitsutils.nim";
    addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, ((x_p1) + ""));
  framePtr = F.prev;

  
}

function addInt__stdZprivateZdigitsutils_u241(result_p0, result_p0_Idx, x_p1) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 116;
    F.filename = "digitsutils.nim";
    addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, BigInt(x_p1));
  framePtr = F.prev;

  
}

function HEX24__systemZdollars_u8(x_p0) {
  var result_369098762 = [[]];

  var F = {procname: "dollars.$", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/system/dollars.nim", line: 0};
  framePtr = F;
    F.line = 19;
    F.filename = "dollars.nim";
    result_369098762[0] = nimCopy(null, [], NTI33554449);
    F.line = 20;
    addInt__stdZprivateZdigitsutils_u241(result_369098762, 0, x_p0);
  framePtr = F.prev;

  return result_369098762[0];

}

function raiseIndexError(i_p0, a_p1, b_p2) {
    var Temporary1;

    if ((b_p2 < a_p1)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32]).concat(HEX24__systemZdollars_u8(i_p0),[32,110,111,116,32,105,110,32],HEX24__systemZdollars_u8(a_p1),[32,46,46,32],HEX24__systemZdollars_u8(b_p2));
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function validateUtf8__pureZunicode_u336(s_p0) {
  var result_738197842 = 0;

  var F = {procname: "unicode.validateUtf8", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/pure/unicode.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 184;
    F.filename = "unicode.nim";
    var i_738197843 = 0;
    F.line = 185;
    var L_738197847 = (s_p0).length;
    Label1: {
      F.line = 186;
        Label2: while (true) {
        if (!(i_738197843 < L_738197847)) break Label2;
          if ((s_p0[chckIndx(i_738197843, 0, (s_p0).length - 1)] <= 127)) {
          F.line = 188;
          i_738197843 = addInt(i_738197843, 1);
          }
          else {
          if (((s_p0[chckIndx(i_738197843, 0, (s_p0).length - 1)] >>> 5) == 6)) {
          if ((s_p0[chckIndx(i_738197843, 0, (s_p0).length - 1)] < 194)) {
          F.line = 190;
          result_738197842 = i_738197843;
          break BeforeRet;
          }
          
          if (((addInt(i_738197843, 1) < L_738197847) && ((s_p0[chckIndx(addInt(i_738197843, 1), 0, (s_p0).length - 1)] >>> 6) == 2))) {
          F.line = 191;
          i_738197843 = addInt(i_738197843, 2);
          }
          else {
            F.line = 192;
            result_738197842 = i_738197843;
            break BeforeRet;
          }
          
          }
          else {
          if (((s_p0[chckIndx(i_738197843, 0, (s_p0).length - 1)] >>> 4) == 14)) {
          if ((((addInt(i_738197843, 2) < L_738197847) && ((s_p0[chckIndx(addInt(i_738197843, 1), 0, (s_p0).length - 1)] >>> 6) == 2)) && ((s_p0[chckIndx(addInt(i_738197843, 2), 0, (s_p0).length - 1)] >>> 6) == 2))) {
          F.line = 195;
          i_738197843 = addInt(i_738197843, 3);
          }
          else {
            F.line = 196;
            result_738197842 = i_738197843;
            break BeforeRet;
          }
          
          }
          else {
          if (((s_p0[chckIndx(i_738197843, 0, (s_p0).length - 1)] >>> 3) == 30)) {
          if (((((addInt(i_738197843, 3) < L_738197847) && ((s_p0[chckIndx(addInt(i_738197843, 1), 0, (s_p0).length - 1)] >>> 6) == 2)) && ((s_p0[chckIndx(addInt(i_738197843, 2), 0, (s_p0).length - 1)] >>> 6) == 2)) && ((s_p0[chckIndx(addInt(i_738197843, 3), 0, (s_p0).length - 1)] >>> 6) == 2))) {
          F.line = 201;
          i_738197843 = addInt(i_738197843, 4);
          }
          else {
            F.line = 202;
            result_738197842 = i_738197843;
            break BeforeRet;
          }
          
          }
          else {
            F.line = 204;
            result_738197842 = i_738197843;
            break BeforeRet;
          }
          }}}
        }
    };
    F.line = 205;
    result_738197842 = (-1);
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_738197842;

}

function validateUtf8__pureZunicode_u7390(s_p0) {
  var result_738204896 = 0;

  var F = {procname: "unicode.validateUtf8", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/pure/unicode.nim", line: 0};
  framePtr = F;
    F.line = 1199;
    F.filename = "unicode.nim";
    result_738204896 = validateUtf8__pureZunicode_u336((s_p0.slice(0, (s_p0).length - 1 + 1)));
  framePtr = F.prev;

  return result_738204896;

}

function nucruneLen(s_p0) {
  var result_738197533 = 0;

  var F = {procname: "unicode.runeLen", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/pure/unicode.nim", line: 0};
  framePtr = F;
    F.line = 52;
    F.filename = "unicode.nim";
    result_738197533 = 0;
    F.line = 53;
    var i_738197534 = 0;
    Label1: {
      F.line = 54;
        Label2: while (true) {
        if (!(i_738197534 < (s_p0).length)) break Label2;
          if ((s_p0[chckIndx(i_738197534, 0, (s_p0).length - 1)] <= 127)) {
          F.line = 55;
          i_738197534 = addInt(i_738197534, 1);
          }
          else {
          if (((s_p0[chckIndx(i_738197534, 0, (s_p0).length - 1)] >>> 5) == 6)) {
          F.line = 56;
          i_738197534 = addInt(i_738197534, 2);
          }
          else {
          if (((s_p0[chckIndx(i_738197534, 0, (s_p0).length - 1)] >>> 4) == 14)) {
          F.line = 57;
          i_738197534 = addInt(i_738197534, 3);
          }
          else {
          if (((s_p0[chckIndx(i_738197534, 0, (s_p0).length - 1)] >>> 3) == 30)) {
          F.line = 58;
          i_738197534 = addInt(i_738197534, 4);
          }
          else {
          if (((s_p0[chckIndx(i_738197534, 0, (s_p0).length - 1)] >>> 2) == 62)) {
          F.line = 59;
          i_738197534 = addInt(i_738197534, 5);
          }
          else {
          if (((s_p0[chckIndx(i_738197534, 0, (s_p0).length - 1)] >>> 1) == 126)) {
          F.line = 60;
          i_738197534 = addInt(i_738197534, 6);
          }
          else {
            F.line = 61;
          i_738197534 = addInt(i_738197534, 1);
          }
          }}}}}
          F.line = 62;
          result_738197533 = addInt(result_738197533, 1);
        }
    };
  framePtr = F.prev;

  return result_738197533;

}

function runeLen__pureZunicode_u7218(s_p0) {
  var result_738204724 = 0;

  var F = {procname: "unicode.runeLen", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/pure/unicode.nim", line: 0};
  framePtr = F;
    F.line = 1166;
    F.filename = "unicode.nim";
    result_738204724 = nucruneLen((s_p0.slice(0, (s_p0).length - 1 + 1)));
  framePtr = F.prev;

  return result_738204724;

}

function nsuRepeatChar(c_p0, count_p1) {
  var result_788530275 = [];

  var F = {procname: "strutils.repeat", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/pure/strutils.nim", line: 0};
  framePtr = F;
    F.line = 1350;
    F.filename = "strutils.nim";
    result_788530275 = nimCopy(null, mnewString(count_p1), NTI33554449);
    Label1: {
      F.line = 1351;
      var i_788530280 = 0;
      F.line = 81;
      F.filename = "iterators_1.nim";
      var colontmp__553648260 = 0;
      F.line = 1351;
      F.filename = "strutils.nim";
      colontmp__553648260 = subInt(count_p1, 1);
      F.line = 96;
      F.filename = "iterators_1.nim";
      var res_553648261 = 0;
      Label2: {
        F.line = 97;
          Label3: while (true) {
          if (!(res_553648261 <= colontmp__553648260)) break Label3;
            F.line = 1351;
            F.filename = "strutils.nim";
            i_788530280 = res_553648261;
            F.line = 1351;
            result_788530275[chckIndx(i_788530280, 0, (result_788530275).length - 1)] = c_p0;
            F.line = 102;
            F.filename = "iterators_1.nim";
            res_553648261 = addInt(res_553648261, 1);
          }
      };
    };
  framePtr = F.prev;

  return result_788530275;

}

function raiseDivByZero() {
    raiseException({message: [100,105,118,105,115,105,111,110,32,98,121,32,122,101,114,111], parent: null, m_type: NTI134217742, name: null, trace: [], up: null}, "DivByZeroDefect");

  
}

function alignString__pureZstrformat_u20(s_p0, minimumWidth_p1, align_p2, fill_p3) {
      var Temporary1;

  var result_687865881 = [];

  var F = {procname: "strformat.alignString", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/pure/strformat.nim", line: 0};
  framePtr = F;
    if ((minimumWidth_p1 == 0)) {
    F.line = 344;
    F.filename = "strformat.nim";
    result_687865881 = nimCopy(null, s_p0, NTI33554449);
    }
    else {
      F.line = 346;
      if ((validateUtf8__pureZunicode_u7390(s_p0) == (-1))) {
      Temporary1 = runeLen__pureZunicode_u7218(s_p0);
      }
      else {
      Temporary1 = (s_p0).length;
      }
      
      var sRuneLen_687865882 = Temporary1;
      F.line = 347;
      var toFill_687865883 = subInt(minimumWidth_p1, sRuneLen_687865882);
      if ((toFill_687865883 <= 0)) {
      F.line = 349;
      result_687865881 = nimCopy(null, s_p0, NTI33554449);
      }
      else {
      if (((align_p2 == 60) || (align_p2 == 0))) {
      F.line = 351;
      result_687865881 = nimCopy(null, (s_p0).concat(nsuRepeatChar(fill_p3, chckRange(toFill_687865883, 0, 2147483647))), NTI33554449);
      }
      else {
      if ((align_p2 == 94)) {
      F.line = 353;
      var half_687865884 = divInt(toFill_687865883, 2);
      F.line = 354;
      result_687865881 = nimCopy(null, (nsuRepeatChar(fill_p3, chckRange(half_687865884, 0, 2147483647))).concat(s_p0,nsuRepeatChar(fill_p3, chckRange(subInt(toFill_687865883, half_687865884), 0, 2147483647))), NTI33554449);
      }
      else {
        F.line = 356;
        result_687865881 = nimCopy(null, (nsuRepeatChar(fill_p3, chckRange(toFill_687865883, 0, 2147483647))).concat(s_p0), NTI33554449);
      }
      }}
    }
    
  framePtr = F.prev;

  return result_687865881;

}

function formatValue__main_u52(result_p0, result_p0_Idx, value_p1) {
  var F = {procname: "formatValue.formatValue", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/pure/strformat.nim", line: 0};
  framePtr = F;
    F.line = 600;
    F.filename = "strformat.nim";
    var value_553648192 = nimCopy(null, value_p1, NTI33554449);
    F.line = 611;
    result_p0[result_p0_Idx].push.apply(result_p0[result_p0_Idx], alignString__pureZstrformat_u20(value_553648192, 0, 0, 32));;
  framePtr = F.prev;

  
}

function makeNimstrLit(c_p0) {
      var result = [];
  for (var i = 0; i < c_p0.length; ++i) {
    result[i] = c_p0.charCodeAt(i);
  }
  return result;
  

  
}

function formatValue__main_u43(result_p0, result_p0_Idx, value_p1) {
  var F = {procname: "formatValue.formatValue", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/pure/strformat.nim", line: 0};
  framePtr = F;
    F.line = 633;
    F.filename = "strformat.nim";
    formatValue__main_u52(result_p0, result_p0_Idx, reprEnum(value_p1, NTI1056964616));
  framePtr = F.prev;

  
}

function readyState__jsZweb95socketZweb95socket_u48(socket_p0) {
  var result_1056964658 = 0;

  var F = {procname: "web_socket.readyState", prev: framePtr, filename: "/root/Projects/42/nimatcha/frontend/js/web_socket/web_socket.nim", line: 0};
  framePtr = F;
    F.line = 34;
    F.filename = "web_socket.nim";
    result_1056964658 = chckRange(socket_p0.readyStateRaw, 0, 3);
  framePtr = F.prev;

  return result_1056964658;

}

function addInt__stdZprivateZdigitsutils_u192(result_p0, result_p0_Idx, x_p1) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 90;
    F.filename = "digitsutils.nim";
    addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, ((x_p1) + ""));
  framePtr = F.prev;

  
}

function HEX24__systemZdollars_u14(x_p0) {
  var result_369098768 = [[]];

  var F = {procname: "dollars.$", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/system/dollars.nim", line: 0};
  framePtr = F;
    F.line = 29;
    F.filename = "dollars.nim";
    result_369098768[0] = nimCopy(null, [], NTI33554449);
    F.line = 30;
    addInt__stdZprivateZdigitsutils_u192(result_369098768, 0, x_p0);
  framePtr = F.prev;

  return result_369098768[0];

}

function formatValue__main_u70(result_p0, result_p0_Idx, value_p1) {
  var F = {procname: "formatValue.formatValue", prev: framePtr, filename: "/root/.choosenim/toolchains/nim-2.2.2/lib/pure/strformat.nim", line: 0};
  framePtr = F;
    F.line = 499;
    F.filename = "strformat.nim";
    result_p0[result_p0_Idx].push.apply(result_p0[result_p0_Idx], HEX24__systemZdollars_u14(value_p1));;
  framePtr = F.prev;

  
}

function main__main_u3() {
  var F = {procname: "main.main", prev: framePtr, filename: "/root/Projects/42/nimatcha/frontend/main.nim", line: 0};
  framePtr = F;
    F.line = 6;
    F.filename = "main.nim";
    var socket_553648132 = new WebSocket("ws://localhost:3000", []);
    F.line = 7;
    Label1: {
      F.line = 7;
      var fmtRes_553648141 = [mnewString(0)];
      F.line = 7;
      fmtRes_553648141[0].push.apply(fmtRes_553648141[0], [115,111,99,107,101,116,46,112,114,111,116,111,99,111,108,61]);;
      F.line = 714;
      F.filename = "strformat.nim";
      add__system_u1942(fmtRes_553648141, 0, socket_553648132.protocol);
    };
    rawEcho(fmtRes_553648141[0]);
    F.line = 8;
    F.filename = "main.nim";
    Label2: {
      F.line = 8;
      var fmtRes_553648155 = [mnewString(0)];
      F.line = 8;
      fmtRes_553648155[0].push.apply(fmtRes_553648155[0], [115,111,99,107,101,116,46,98,105,110,97,114,121,84,121,112,101,61]);;
      F.line = 714;
      F.filename = "strformat.nim";
      add__system_u1942(fmtRes_553648155, 0, socket_553648132.binaryType);
    };
    rawEcho(fmtRes_553648155[0]);
    F.line = 9;
    F.filename = "main.nim";
    Label3: {
      F.line = 9;
      var fmtRes_553648160 = [mnewString(0)];
      F.line = 9;
      fmtRes_553648160[0].push.apply(fmtRes_553648160[0], [115,111,99,107,101,116,46,117,114,108,61]);;
      F.line = 714;
      F.filename = "strformat.nim";
      add__system_u1942(fmtRes_553648160, 0, socket_553648132.url);
    };
    rawEcho(fmtRes_553648160[0]);
    F.line = 10;
    F.filename = "main.nim";
    Label4: {
      F.line = 10;
      var fmtRes_553648165 = [mnewString(0)];
      F.line = 10;
      fmtRes_553648165[0].push.apply(fmtRes_553648165[0], [115,111,99,107,101,116,46,101,120,116,101,110,115,105,111,110,115,61]);;
      F.line = 714;
      F.filename = "strformat.nim";
      add__system_u1942(fmtRes_553648165, 0, socket_553648132.extensions);
    };
    rawEcho(fmtRes_553648165[0]);
    F.line = 11;
    F.filename = "main.nim";
    Label5: {
      F.line = 11;
      var fmtRes_553648170 = [mnewString(0)];
      F.line = 11;
      fmtRes_553648170[0].push.apply(fmtRes_553648170[0], [115,111,99,107,101,116,46,114,101,97,100,121,83,116,97,116,101,61]);;
      F.line = 11;
      formatValue__main_u43(fmtRes_553648170, 0, readyState__jsZweb95socketZweb95socket_u48(socket_553648132));
    };
    rawEcho(fmtRes_553648170[0]);
    F.line = 12;
    Label6: {
      F.line = 12;
      var fmtRes_553648197 = [mnewString(0)];
      F.line = 12;
      fmtRes_553648197[0].push.apply(fmtRes_553648197[0], [115,111,99,107,101,116,46,98,117,102,102,101,114,101,100,65,109,111,117,110,116,61]);;
      F.line = 12;
      formatValue__main_u70(fmtRes_553648197, 0, socket_553648132.bufferedAmount);
    };
    rawEcho(fmtRes_553648197[0]);
  framePtr = F.prev;

  
}
var F = {procname: "module main", prev: framePtr, filename: "/root/Projects/42/nimatcha/frontend/main.nim", line: 0};
framePtr = F;
F.line = 15;
F.filename = "main.nim";
main__main_u3();
framePtr = F.prev;
var F = {procname: "module main", prev: framePtr, filename: "/root/Projects/42/nimatcha/frontend/main.nim", line: 0};
framePtr = F;
framePtr = F.prev;
